
dist: trusty
sudo: required
language: cpp

cache: ccache
addons:
  apt:
    update: false

install:
  - docker run -d --name build-env -v $(pwd):/home/boomerang/boomerang/ -v /home/travis/.ccache/:/home/boomerang/.ccache ceeac/boomerang-build-base:latest tail -f /dev/null

script:
  - docker exec -t build-env bash -c "cd boomerang &&
    mkdir build &&
    cd build &&
    cmake -DBOOMERANG_BUILD_UNIT_TESTS=ON .. &&
    make -j$(nproc) &&
    make test"

notifications:
  email: false

