#
# This file is part of the Boomerang Decompiler.
#
# See the file "LICENSE.TERMS" for information on usage and
# redistribution of this file, and for a DISCLAIMER OF ALL
# WARRANTIES.
#

version: "Build {build}"

platform:
  - x64

os:
  - Visual Studio 2017
  - Visual Studio 2019

configuration:
  - Debug
  - Release

# Only build VS2017 Debug and VS2019 Release builds to keep build times down
matrix:
  fast_finish: true
  exclude:
    - os: Visual Studio 2017
      configuration: Release
    - os: Visual Studio 2019
      configuration: Debug

branches:
  except:
    - gh-pages

skip_commits:
  message: /\[[aA]ppveyor [sS]kip\]/

clone_folder: C:\projects\boomerang

build:
  parallel: true
  verbosity: quiet # MSBuild verbosity level (quiet|minimal|normal|detailed)

pull_requests:
  do_not_increment_build_number: true

init:
  - cmd: cmake --version
  - cmd: msbuild /version

before_build:
  - ps: cd C:\projects\boomerang
  - ps: mkdir build
  - ps: cd build
  - ps: ..\scripts\appveyor-generate.ps1

build_script:
  - cmake --build . --target PACKAGE # this includes ALL

test_script:
  - cmake --build . --target RUN_TESTS

artifacts:
  - path: 'build\boomerang-*.exe'
    name: Installer
    type: File
  - path: 'build\boomerang-*.zip'
    name: Portable ZIP
    type: File
