version: "Build {build}"


cache: c:\tools\vcpkg\installed\

branches:
  except:
    - gh-pages


matrix:
  fast_finish: true


pull_requests:
  do_not_increment_build_number: true


clone_folder: C:\projects\boomerang


os:
  - Visual Studio 2017


platform:
  - x64


configuration:
  - Debug
  - Release


build:
  parallel: true
  verbosity: quiet # MSBuild verbosity level (quiet|minimal|normal|detailed)



clone_folder: C:\projects\boomerang

build:
  parallel: true
  verbosity: quiet # MSBuild verbosity level (quiet|minimal|normal|detailed)

matrix:
  fast_finish: true

init:
  - cmd: cmake --version
  - cmd: msbuild /version

before_build:
  - ps: cd C:\projects\boomerang
  - ps: mkdir build
  - ps: cd build
  - ps: ..\scripts\appveyor-generate.ps1

build_script:
  - cmake --build . --target PACKAGE # this includes ALL

test_script:
  - cmake --build . --target RUN_TESTS

artifacts:
  - path: 'build\boomerang-*.exe'
    name: Installer
    type: File
  - path: 'build\boomerang-*.zip'
    name: Portable ZIP
    type: File

